console.log((0).__proto__ === Number.prototype)
console.log(false.__proto__ === Boolean.prototype)
console.log((new Date()).__proto__ === Date.prototype)
console.log((function(){}/* new Function */).__proto__ === Function.prototype)
console.log("string".__proto__ === String.prototype)
console.log({}.__proto__ === Object.prototype)
console.log((function () {}).prototype)
console.log((class {}).prototype)
console.log(Object.prototype.__proto__)
console.log(Object.prototype.__proto__)
